name: Build Docker image and push to ECR

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" # The only supported region for public ECR

      - name: Packer init
        run: packer init ./packer.pkr.hcl
        env:
          PACKER_LOG: 1

      - name: Packer validate
        run: packer validate -syntax-only packer.pkr.hcl
        env:
          PACKER_LOG: 1

      - name: Build docker image
        run: packer build -var image_tag=${{ github.event.release.tag_name }} .
        env:
          PACKER_LOG: 1
          PKR_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          PKR_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PKR_VAR_ecr_url: ${{ secrets.AWS_ECR_URL }}
